### PR TITLE
Updated shine_scd() so that it takes a dataset (directory) as an argument

### PR DESCRIPTION
**Pull request by manchen07**
`shine_scd()` is now updated to allow specifying a .csv, .xlsx, or .txt data file. If you call the function in RStudio with:

`
shine_scd(dataset = ".../xxx.csv")
`

The app will open with the dataset already loaded. 

I think the code could be simplified and improved, but just want you to double check the current updates first.

### CODE REVIEW

**Review by jepusto — CHANGES_REQUESTED** [review]
This approach seems to work fine, but one downside is that the app can only be used on one dataset if you call it with the `dataset = ` argument. Would it be possible to accomplish using the `dataset = ` argument without losing the ability to upload a new dataset from within the app? 

It seems like it might be possible to do this by turning lines 43-65 of `ui.R` into dynamically computed uiOutput. The idea would be to create this chunk of the UI in server.R, with default values that depend on whether `is.null(dataset)`. If the `dataset` argument is provided, then:

* the `dat_type` default value would be set based on the file extension of `dataset`
* the `dat` fileInput or `xlsx` fileInput default value would be set to the value of `dataset`, accordingly. 
* everything else would remain as-is

I think if this worked, then it would still allow the user to change the `dat_type` or fileInput box from within the Shiny app, as well as to change the values of `header`, `sep`, and `quote` if, for example, they upload a `.txt` file that actually uses commas as separators, or if they upload an `xlsx` file with multiple sheets and want to use a sheet other than the first one.

**Comment by manchen07** [comment]
When we call `shine_scd()` with the `dataset =` argument, `Use the current loaded dataset` will be added and set as the default option to the `radioButtons`. This can be done by:

`
if (!is.null(dataset)) {
        updateRadioButtons(session, "dat_type", choices = new_choices, selected = "UseCurrentData")
      }
`

However, I am not sure if we will be able to select other options, like `Upload data from a .csv or .txt file`, because `!is.null(dataset)` is always true and thus `Use the current loaded dataset` will always be selected by default.

We might need to somehow remove the loaded `dataset` from the server environment if we want to load a new dataset. If so, we might need to add a new button or check box.

**Comment by jepusto** [comment]
Would it make sense to handle the default and options when the radio button is first created, instead of with updateRadioButtons()?

**Comment by manchen07** [comment]
> Would it make sense to handle the default and options when the radio button is first created, instead of with updateRadioButtons()?
> […](#)
> Sent from my iPhone
> On Sep 17, 2020, at 6:16 PM, Man Chen ***@***.***> wrote: When we call shine_scd() with the dataset = argument, Use the current loaded dataset will be added and set as the default option to the radioButtons. This can be done by: if (!is.null(dataset)) { updateRadioButtons(session, "dat_type", choices = new_choices, selected = "UseCurrentData") } However, I am not sure if we will be able to select other options, like Upload data from a .csv or .txt file, because !is.null(dataset) is always true and thus Use the current loaded dataset will always be selected by default. We might need to somehow remove the loaded dataset from the server environment if we want to load a new dataset. If so, we might need to add a new button or check box. — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, we can do that. But setting up the default and options still depends on whether there is a `dataset` in the server environment. Then the radio button cannot not be used to trigger the replacement of the dataset with any new dataset. For example, if we call `shine_scd(data = path)`, the new option (`Use the current loaded data`) of the radio button will be selected by default. Then if we try to click on other options, this move will not be caught using the radio button itself unless we remove the `dataset`  and the default option first.

I will think more about this.

**Comment by jepusto** [comment]
Really? That seems weird. If you push what you’ve tried I’ll take a look and see what’s going on.

**Comment by manchen07** [comment]
I created separate radioButtons depending on whether there is a `dataset` in ui.R. Things seem working now. Let me know if you find any issues or errors.

**Comment by jepusto** [comment]
I pushed another set of changes that streamline things a bit and remove some redundancy. Could you take a look and verify that things seem to be working?

**Comment by manchen07** [comment]
It seems that if you set the `dataset` argument to an `xlsx` file, the app still could not read the sheet names. Maybe `excel_sheets()` is not returning the sheet names of the dataset?

**Comment by jepusto** [comment]
I think it is a problem with the sheetname reactive object (lines 57-67)
and the observer right below it (lines 69-73). The observer is getting
called when sheetnames is blank, so the inSelect dropdown gets updated with
no choices to select from.

**Comment by manchen07** [comment]
I added `observeEvent()` and it seems working?

**Comment by manchen07** [comment]
Never mind. It is still not working...

**Comment by jepusto** [comment]
I tried moving things back over to conditionalInput() instead. Still not
working though. Be sure to pull the latest.

**Comment by manchen07** [comment]
Okay! Will continue during weekends.

**Comment by jepusto** [comment]
I have an idea about a different strategy for this. Let me push another change before you do anything further.

**Comment by jepusto** [comment]
Hi Man, could you please take a look at the latest push and see if it works? Also please debug any namespace issues or other errors showing up in the package checks.

**Comment by manchen07** [comment]
Sure. Thanks for pushing the new strategy!

**Comment by manchen07** [comment]
A quick question:

Do you still want to allow users to choose which sheet they want to use if they load a excel file within `shine_scd()`, or to choose the `header`, `sep` or `quote` if they load a `.txt` file?

**Comment by jepusto** [comment]
With the revised approach, they’ll have to specify those details as part of the call, e.g.:

shine_scd(“some_scds.xlsx”, sheet = “Carson”)

**Comment by manchen07** [comment]
Everything looks good except that when I do `shine_scd("some_scds.xlsx", sheet = "Carson")`, I cannot specify the baseline and treatment levels. It shows `c("B", "A")` for both baseline level and treatment level. It looks like the filtering variables option also does not work. Do you get same errors?

**Comment by jepusto** [comment]
I think I found the source of the problem. In the shine_scd() function, I
was calling readxl::read_excel(), which creates a tibble. When an xlsx file
is read in from within the app, I call the same function but then call
as.data.frame() on the result. I added as.data.frame() to the call in
shine_scd(), and it seems to be working now. Could you please verify that
this resolves the issue?

**Comment by manchen07** [comment]
Yes I think adding `as.data.frame()` solved the issue. Everything looks great now. We might need to remind users that the data input in `shine_scd()` follows the way `read_xlsx()` or `read.csv()` or `read.table()` reads in data. For example, if their `.txt` file has header, they need call the function like `shine_scd("someData.txt", header = TRUE)`.

**Pull request merged**
