### PR TITLE
Wrapper function

### PR DESCRIPTION
**Pull request by manchen07**
This pull request is about the wrapper function (single calculation) for fitting `lme()` model and calculating `g_mlm()` (#8). Please let me know if any change or update is needed. Thank you!

### CODE REVIEW

**Review by jepusto — CHANGES_REQUESTED** [review]
This looks really good! I have a few follow-up questions/requests:

1. Please add some tests with more complex functional forms (not just `FE_base = FE_trt = RE_base = RE_trt = 0`). 
2. Please also add an example or two with more complex functional forms.
3. Should we return an indicator for model convergence in the summary output?
4. What do you think of exporting `default_times()`?
5. One scenario that we might want to consider is if a user wanted to use the default starting time-point (`A`) but a fixed, non-default duration of follow-up. For instance, use default `A` but set `B = A + 10`. Would there be any way to reconfigure `calc_BCSMD()` to allow for this?

**Comment by manchen07** [comment]
Thank you for those follow-up questions/requests. I think I've worked on all of them, but please let me know if I miss anything or further updates or corrections are needed. I have a few questions:

1. Given that `default_times()` uses similar syntax as `preprocess_SCD()`, I'm curious if we should calculate default times inside `preprocess_SCD()`. It seems that we could think of calculating default times as part of data preprocessing, although I do prefer a separate function for calculating default times.
2. Maybe I'm missing something, but it seems that `covg_warn <- !is.null(attr(m_fit, "warning"))` in `g_REML()` or `g_mlm()` is not returning whether RML estimation has converged or not because `attr(m_fit, "warning")` seems to be NULL all the time.
3. I messed up the A and B in the Bryant example of the three-level paper... It's definitely a great idea to export `default_times()`. We would need to update this function in the shiny app, after you review everything. Thanks!

**Comment by manchen07** [comment]
And I'm sorry I did not have time for the batch calculation. I'll try to work on that next week.

**Comment by jepusto** [comment]
> 1. Given that `default_times()` uses similar syntax as `preprocess_SCD()`, I'm curious if we should calculate default times inside `preprocess_SCD()`. It seems that we could think of calculating default times as part of data preprocessing, although I do prefer a separate function for calculating default times.

I think it's probably fine as is. Adding the default times to the `preprocess_SCD()` output would complicate the output (either with extra variables or additional attributes on the dataset). If the user wants to use the default times, then it seems reasonable that they would call `default_times()` directly.

**Comment by jepusto** [comment]
> 2. Maybe I'm missing something, but it seems that `covg_warn <- !is.null(attr(m_fit, "warning"))` in `g_REML()` or `g_mlm()` is not returning whether RML estimation has converged or not because `attr(m_fit, "warning")` seems to be NULL all the time.

I agree that this isn't currently working correctly. I added some tests for the correct behavior, but haven't figured out how to fix it yet.

**Comment by jepusto** [comment]
> 3. I messed up the A and B in the Bryant example of the three-level paper... It's definitely a great idea to export `default_times()`. We would need to update this function in the shiny app, after you review everything. Thanks!

Let's discuss next time we meet.

**Review by jepusto — APPROVED** [review]

**Pull request merged**
