### PR TITLE
Backlog cleaning

### PR DESCRIPTION
**Pull request by bethanyhamilton**
#25, #19, #20, #13

### CODE REVIEW

**Comment by jepusto** [comment]
I pushed a few little changes to this branch, so be sure to pull again.

**Comment by jepusto** [comment]
Thanks. I am still getting errors when trying to load the Thorne data in the shiny app. Could you take a look?

**Comment by bethanyhamilton** [comment]
Of course! I'm not exactly sure what is going on. I think the error might
have been there before since it is in the master version of the app as
well. It must be an issue with the was that it is subsetting.

-Bethany

**Comment by bethanyhamilton** [comment]
Error fixed. exampleMapping for Thorne had incorrectly labeled the phase variable as "condition" instead of "phase_id". That's why the example was not working while Thorne.csv was working.

**Pull request merged**
