### PR TITLE
Code for syntax tab. Still some issues I need to work out. For treatm…

### PR DESCRIPTION
**Pull request by bethanyhamilton**
…ent reversal/RML there is some bug. Also, if you do not specify an arguement in a function, I need to drop that from the syntax.

### CODE REVIEW

**Comment by jepusto** [comment]
This is definitely coming together! I have one main request/suggestion, which I think will make this feature a bit easier to maintain and keep updating. Rather than building all of the R code inside the shiny app server, what if you use separate files with chunks of R code that can be parsed? An example of how this could work (be sure to pull the latest commit of this branch before running):
```r
example_code <- 
    readLines("inst/shiny-examples/scdhlm/code-chunks/load-example.R") %>% 
    paste(collapse = "\n") %>%
    glue::glue_data(list(example_name = "Lambert"), .)

excel_code <- 
    readLines("inst/shiny-examples/scdhlm/code-chunks/load-excel.R") %>% 
    paste(collapse = "\n") %>%
    glue::glue_data(list(user_path = '"auxilliary/Some SCDs.xlsx"', user_sheet = '"Carson"'), .)
```
In the above examples, the values in the named lists would come from variables determined within the shiny app (e.g., `example_name` would be set equal to `input$example`). Then once we've got the code chunks parsed, just paste all relevant chunks together and output to the app.

As I'm writing this out, wondering if it would be even easier to use a helper function something like
```r
parse_code_chunk <- function(chunk, args) {
  raw_code <- readLines(paste0("inst/shiny-examples/scdhlm/code-chunks/", chunk, ".R")
  code_chunk <- paste(raw_code, collapse = "\n")
  glue::glue_data(.x = args, code_chunk)  
}

parse_code_chunk("load-example", args = list(example_name = "Lambert"))
parse_code_chunk("load-excel", args = list(user_path = '"auxilliary/Some SCDs.xlsx"', user_sheet = '"Carson"'))
```

**Comment by jepusto** [comment]
It would also be nice to have a button to send the code to the RStudio code pane or at least copy to clipboard, along the lines of
https://gist.github.com/jimhester/18b9116a415633e5a73d

**Comment by jepusto** [comment]
One last comment: I added an additional step in the data cleaning code, which rounds the `session` variable to the nearest integer if `input$round_session` is `TRUE`. Could you add this to the script?

(This sort of thing is why I'm concerned about being able to easily maintain/update this feature of the app.)

**Review by jepusto — COMMENTED** [review]
@bethanyhamilton could you please briefly describe the remaining issues with the code? How can I reproduce them?

**Comment by jepusto** [comment]
@manchen07 At some point next week, could you please take a look at Bethany's work here and help to resolve any conflicts with the main branch, so that it can be pulled in? Also please review for any remaining issues.

**Comment by manchen07** [comment]
Sure. I will work on this after updating the Intro for three level BC-SMD.

—
Man Chen (she/her/hers)
Quantitative Methods
Department of Educational Psychology
University of Wisconsin-Madison
________________________________

**Comment by manchen07** [comment]
I hope the conflicts with master branch are resolved now. @bethanyhamilton We need to debug line 553-609 in server.R. Everything before line 553 seems working fine.

**Comment by manchen07** [comment]
@jepusto The code for Syntax tab is updated. Could you please double check if everything works fine?

**Review by jepusto — APPROVED** [review]

**Comment by jepusto** [comment]
Closes #30.

**Pull request merged**
